### ISSUE TITLE
カード作成で改行入れ忘れる人が多いと思ったら...

### ISSUE THREAD

**Issue by nichesuch** [ak2ie/mama-minesweeper#107]
![image](https://user-images.githubusercontent.com/2096703/171305922-6fcc206b-c490-47e4-a448-3f8853cd1aca.png)

**Comment by kaizumaki** [comment]
そっか、inputやbutton群がbottomにfixedになっているから、イラストが隠れてしまうんですね。
素直に全体をスクロールさせるほうがいいでしょうか？

**Comment by nichesuch** [comment]
@kaizumaki それでも、端末によっては隠れてしまうと思われます。
NGワード確認後に出る`保存しますか？`のダイアログに画像を入れられないでしょうか？

まあ、もうそんなに見られていないので、実施するかは検討の余地ありますが。

**Comment by kaizumaki** [comment]
これはアーカイブする前にやってしまいましょう。
「fixedをやめる」というのと「確認ダイアログに画像を表示する」の両面で試してみますね。
