### ISSUE TITLE
作家さんのリンクを追加する

### ISSUE THREAD

**Issue by ak2ie** [ak2ie/mama-minesweeper#12]
漫画作家さんのHPなどへのリンクを追加する

**Comment by nichesuch** [comment]
> ご本人の希望としては、
> もし複数貼ることが可能であれば、Litlinkに加えて
> ①Instagram
> ②Twitter
> ③ブログHP
> を追加していただければ嬉しいとのことでした。数字は希望順位とのことです。
> そこまで沢山は貼れなければ、Litlinkだけでも
> 構いません、とのことでしたので、ご検討頂ければと思います。

[litlink](https://lit.link/shiromemisae)
[Instagram](https://www.instagram.com/misae_mon/)
[Twitter](https://twitter.com/misae_yjm)
[ブログHP](https://hibishirome.nbblog.jp/)
