### ISSUE TITLE
ゲーム実施までの流れ　ゲームID入力について

### ISSUE THREAD

**Issue by nichesuch** [ak2ie/mama-minesweeper#44]
## 前提

- ゲームは誰かしらが作らないと実施できない。
- 作者は誰でも良いわけではなく、身近な人（基本的に奥さんを想定）でないとあまり意味がない。
- 設定画面でゲームを作るとURLが発行される。
- URLの最後の部分がゲームID。

## 課題

- URLを旦那さんに渡す方法が明確でない。https://github.com/ak2ie/mama-minesweeper/issues/13#issuecomment-1113069802
- 旦那さんがTOPページに来た時にどうやって自分の奥さんのゲームを開始するか、明確でない。
- 奥さんがゲームを作る際に、どんなゲームなのか分からずに作ることになる。

## 改修案

- `あそぶ`ではなく`試す`にして、デフォルトのゲームができるようにする。
- ゲーム作成後、URLを旦那に送れるようにする。ゲームIDを入力することはない。

**Comment by nichesuch** [comment]
旦那さんへのシェアはWeb Share APIを使ってみようと思いますが、どうでしょうか？
https://qiita.com/TK-C/items/cfa9f15e45b9e9f0e9a1

**Comment by kaizumaki** [comment]
> 旦那さんへのシェアはWeb Share APIを使ってみようと思いますが、どうでしょうか？ https://qiita.com/TK-C/items/cfa9f15e45b9e9f0e9a1

おお、任意の宛先にシェアできるのですね。いいと思います！

**Comment by nichesuch** [comment]
対応ブラウザ少なそうなので、対応していなかったらClipbordが使えるようにしておきます。
https://qiita.com/at-946/items/aea8ac9938d810feae7b
