### ISSUE TITLE
動作が重い

### ISSUE THREAD

**Issue by kaizumaki** [ak2ie/mama-minesweeper#49]
storageの `listAll()` がだいぶ重いことは予想つくのですが、他の動作も全体的に重い感じがしますね。

**Comment by kaizumaki** [comment]
案：ローディングを入れる

**Comment by nichesuch** [comment]
@kaizumaki 対応お願いします！

**Comment by kaizumaki** [comment]
- [x] カード作成用のイラスト画像ファイルの解像度を落とす
- [x] storageの `listAll()` をやめて `list()` にする
- [x] カード選択はカルーセルUIをやめて、ひとつのリスト表示にする

**Comment by kaizumaki** [comment]
モバイル実機（iPhone/iPad Air Safari）の動作がまだ重いので、引き続き調査中。

**Comment by kaizumaki** [comment]
動作が重いのはgoogle fontsのimportが原因でした。 #80 のPRでかなりサクサク動くようになりました。

**Comment by kaizumaki** [comment]
カード画像ファイル読み込みのもっさり感は、html2canvasによる画像生成に問題がある模様。

**Comment by kaizumaki** [comment]
#101 でかなり改善されたと思うので、一旦こちらのissueはクローズします。
